# Generated by Django 3.0.6 on 2021-02-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foglalkozas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tanulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=128)),
                ('felhasznalonev', models.CharField(max_length=128)),
                ('jelszo', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Valasztas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglalkozas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsoapp.Foglalkozas')),
                ('tanulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsoapp.Tanulo')),
            ],
        ),
    ]
