# Generated by Django 3.0.6 on 2021-02-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanulo',
            old_name='felhasznalonev',
            new_name='fnev',
        ),
    ]
