# Generated by Django 3.0.6 on 2021-02-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0003_foglalkozas_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foglalkozas',
            options={'verbose_name': 'Foglalkozás', 'verbose_name_plural': 'Foglalkozások'},
        ),
        migrations.AlterModelOptions(
            name='tanulo',
            options={'verbose_name': 'Tanuló', 'verbose_name_plural': 'Tanulók'},
        ),
        migrations.AlterModelOptions(
            name='valasztas',
            options={'verbose_name': 'Választás', 'verbose_name_plural': 'Választások'},
        ),
        migrations.RenameField(
            model_name='foglalkozas',
            old_name='db',
            new_name='maxdb',
        ),
    ]
