# Generated by Django 3.0.6 on 2021-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0004_auto_20210223_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='foglalkozas',
            name='db',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
