# Generated by Django 3.0.6 on 2021-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0005_foglalkozas_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='foglalkozas',
            name='db2',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
