# Generated by Django 3.0.6 on 2021-02-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0006_foglalkozas_db2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foglalkozas',
            name='db2',
        ),
    ]
